@startuml
|#AntiqueWhite|教务处|
start
:安排课表;
:课表]
|#AntiqueWhite|教师|
:选课;
|#AntiqueWhite|学生|
:选课;
|教师|
:安排平时实验;
:打印审批表;
|教务处|
:审核实验安排;
:审批签字;
|教师|
:发布实验内容;
|学生|
:完成实验内容;
|教师|
:批改实验;
'|#AntiqueWhite|系统|
':记录分数并且求取平均值;
|学生|
:查询实验分数;

stop

@enduml