@startuml

class 教师类 {
姓名
性别
职工编号
职称
{abstract}
安排实验()
批改实验()
选课()
}

class 学生类{
姓名
学号
性别
专业
年级
班级
平均成绩
{abstract}
选课()
完成实验内容()
查询实验成绩()
}

class 课程类{
课程号
课程名
学年
学期
}

class 实验类{
实验序号
实验名称
实验内容
实验成绩
实验评价
}

class 教务处类{
学院
主任
{abstract}
安排课程()
审核实验()
}

class 账号类{
用户ID
真实姓名
github姓名
密码
}

学生类 "1" --> "N" 实验类 :完成实验内容
教师类 "1" --> "N" 实验类 :批改实验，安排实验
学生类 "N" --> "N" 课程类 :选课
教师类 "1" --> "N" 课程类 :选课
课程类 "1" -- "N" 实验类
教务处类 "1" --> "N" 课程类
教务处类 "1" --> "N" 账号类
教师类 "1" --> "N" 账号类
学生类 "1" --> "N" 账号类


@enduml