@startuml

class 借书记录{
书籍编号
借书日期
还书日期
逾期记录
逾期时间
续借时间
}

class 图书管理员{
职工号
姓名
薪资
工作班次
}

class 图书藏品{
书籍名称
书籍编号
ISBN编号
作者
出版社
简介
价格
总库存量
可借数量
}

class 读者{
姓名
身份证号
借书卡号
借书记录
}

class 黑名单{
姓名
身份证号
借书卡号
违规记录
}

图书管理员  "1" -- "N" 借书记录 : 登记
图书管理员  "1" -- "N" 黑名单 : 登记
图书管理员  "1" -- "N" 图书藏品 : 管理
图书管理员  "1" -- "N" 读者 : 信息登记
图书藏品   --  借书记录
读者  "1" --> "0..3" 借书记录


@enduml