@startuml
left to right direction

actor 图书管理员
actor 读者
rectangle  {
图书管理员 --> (图书管理)
图书管理员 --> (借阅图书)
图书管理员 --> (逾期处理)
图书管理员 --> (续借图书)
图书管理员 --> (借阅卡办理)
图书管理员 --> (还书)
(还书).>(借阅图书):extends
(续借图书).>(借阅图书):extends
(借阅图书).>(借阅卡办理):extends
(借阅图书) <-- 读者
(还书) <-- 读者
(续借图书) <-- 读者
(逾期处理)<--读者
(借阅卡办理)<--读者

}

@enduml