@startuml

actor 教师 as A
participant "实验" as B
participant "教务处" as C
participant "系统" as D

activate A
A -> B :设计安排实验内容
deactivate A
activate B


B -> C :提交实验安排情况供审核
deactivate B
activate C

C -> A :审核通过
deactivate C
activate A

A->D:公布实验内容和安排
deactivate A

@enduml